-- Crowd report table for predicted/observed occupancy.
create table if not exists public.crowd_reports (
  id bigint generated by default as identity primary key,
  stop_id text not null,
  occupancy_level smallint not null check (occupancy_level between 0 and 3),
  source_type text not null default 'predicted',
  created_at timestamptz not null default now()
);

-- Migrate older schema if it still uses station_id.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'crowd_reports'
      and column_name = 'station_id'
  ) then
    alter table public.crowd_reports rename column station_id to stop_id;
  end if;
end $$;

create index if not exists idx_crowd_reports_stop_created_at
on public.crowd_reports (stop_id, created_at desc);

alter table public.crowd_reports enable row level security;

-- App clients can read latest predictions.
drop policy if exists "anon can read crowd reports" on public.crowd_reports;
create policy "anon can read crowd reports"
on public.crowd_reports
for select
to anon
using (true);

-- App users can submit crowd reports from mobile client.
drop policy if exists "anon can insert user crowd reports" on public.crowd_reports;
create policy "anon can insert user crowd reports"
on public.crowd_reports
for insert
to anon
with check (
  source_type = 'user'
  and occupancy_level between 0 and 3
);
