-- Hourly crowd forecast table generated from ridership trends.
create table if not exists public.crowd_forecast_hourly (
  id bigint generated by default as identity primary key,
  stop_id text not null,
  forecast_hour smallint not null check (forecast_hour between 0 and 23),
  is_weekend boolean not null,
  occupancy_level smallint not null check (occupancy_level between 0 and 3),
  occupancy_percent numeric(5,2) not null check (occupancy_percent between 0 and 100),
  expected_wait_minutes smallint not null default 4 check (expected_wait_minutes between 0 and 60),
  eta_multiplier numeric(4,2) not null default 1.00 check (eta_multiplier between 1.00 and 3.00),
  source_type text not null default 'trend_model',
  updated_at timestamptz not null default now(),
  unique (stop_id, forecast_hour, is_weekend)
);

update public.crowd_forecast_hourly
set
  stop_id = public.normalize_stop_id(stop_id),
  source_type = lower(trim(source_type))
where true;

create index if not exists idx_crowd_forecast_stop_hour_weekend
on public.crowd_forecast_hourly (stop_id, forecast_hour, is_weekend);

do $$
begin
  alter table public.crowd_forecast_hourly
    add constraint crowd_forecast_hourly_stop_fk
    foreign key (stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

alter table public.crowd_forecast_hourly enable row level security;

drop policy if exists "anon can read hourly crowd forecasts" on public.crowd_forecast_hourly;
create policy "anon can read hourly crowd forecasts"
on public.crowd_forecast_hourly
for select
to anon, authenticated
using (true);
