-- Run these blocks in order inside the Supabase SQL Editor.

-- 0) stop_catalog_setup.sql
create or replace function public.normalize_stop_id(value text)
returns text
language sql
immutable
as $$
  select upper(trim(coalesce(value, '')))
$$;

create table if not exists public.transit_stops (
  stop_id text primary key,
  stop_name text not null,
  stop_lat double precision,
  stop_lon double precision,
  route_id text not null,
  category text,
  synced_at timestamptz not null default now()
);

create index if not exists idx_transit_stops_route_id
on public.transit_stops (route_id);

insert into public.transit_stops (
  stop_id,
  stop_name,
  stop_lat,
  stop_lon,
  route_id,
  category,
  synced_at
)
select distinct on (public.normalize_stop_id(ts.stop_id))
  public.normalize_stop_id(ts.stop_id) as stop_id,
  trim(coalesce(ts.stop_name, public.normalize_stop_id(ts.stop_id))) as stop_name,
  ts.stop_lat,
  ts.stop_lon,
  upper(trim(coalesce(ts.route_id, 'N/A'))) as route_id,
  nullif(trim(coalesce(ts.category, '')), '') as category,
  now() as synced_at
from public.train_stops_kl ts
where public.normalize_stop_id(ts.stop_id) <> ''
order by public.normalize_stop_id(ts.stop_id), trim(coalesce(ts.stop_name, ''))
on conflict (stop_id) do update
set
  stop_name = excluded.stop_name,
  stop_lat = excluded.stop_lat,
  stop_lon = excluded.stop_lon,
  route_id = excluded.route_id,
  category = excluded.category,
  synced_at = now();

-- 1) route_connections_setup.sql
create table if not exists public.route_connections (
  id bigint generated by default as identity primary key,
  from_stop_id text not null,
  to_stop_id text not null,
  route_id text not null,
  connection_type text not null default 'standard_stop',
  travel_time_minutes integer not null default 2,
  created_at timestamptz not null default now(),
  unique (from_stop_id, to_stop_id, route_id, connection_type)
);

update public.route_connections
set
  from_stop_id = public.normalize_stop_id(from_stop_id),
  to_stop_id = public.normalize_stop_id(to_stop_id),
  route_id = upper(trim(route_id)),
  connection_type = lower(trim(connection_type))
where true;

create index if not exists idx_route_connections_from_stop
on public.route_connections (from_stop_id);

create index if not exists idx_route_connections_to_stop
on public.route_connections (to_stop_id);

do $$
begin
  alter table public.route_connections
    add constraint route_connections_from_stop_fk
    foreign key (from_stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.route_connections
    add constraint route_connections_to_stop_fk
    foreign key (to_stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

alter table public.route_connections enable row level security;

drop policy if exists "route_connections_select_anon" on public.route_connections;
create policy "route_connections_select_anon"
  on public.route_connections
  for select
  to anon, authenticated
  using (true);

select count(*) as route_connections_count
from public.route_connections;

-- 2) find_route_rpc_setup.sql
create or replace function public.find_route(start_stop text, end_stop text)
returns table(path_array text[], total_time integer)
language sql
security definer
set search_path = public
as $$
  with recursive params as (
    select
      public.normalize_stop_id(start_stop) as start_id,
      public.normalize_stop_id(end_stop) as end_id
  ),
  paths as (
    select
      array[rc.from_stop_id, rc.to_stop_id]::text[] as path_array,
      rc.to_stop_id as current_stop,
      rc.travel_time_minutes as total_time,
      1 as depth
    from public.route_connections rc
    join params p on rc.from_stop_id = p.start_id

    union all

    select
      path.path_array || rc.to_stop_id,
      rc.to_stop_id as current_stop,
      path.total_time + rc.travel_time_minutes as total_time,
      path.depth + 1 as depth
    from paths path
    join public.route_connections rc
      on rc.from_stop_id = path.current_stop
    where path.depth < 40
      and not (rc.to_stop_id = any (path.path_array))
  )
  select
    path.path_array,
    path.total_time
  from paths path
  join params p on true
  where path.current_stop = p.end_id
  order by total_time asc, cardinality(path_array) asc
  limit 1;
$$;

grant execute on function public.find_route(text, text) to anon, authenticated;

-- 3) crowd_reports_setup.sql
create table if not exists public.crowd_reports (
  id bigint generated by default as identity primary key,
  stop_id text not null,
  occupancy_level smallint not null check (occupancy_level between 0 and 5),
  source_type text not null default 'predicted',
  created_at timestamptz not null default now()
);

update public.crowd_reports
set
  stop_id = public.normalize_stop_id(stop_id),
  source_type = lower(trim(source_type))
where true;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'crowd_reports'
      and column_name = 'source_type'
  ) then
    alter table public.crowd_reports
      drop constraint if exists crowd_reports_source_type_check;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'crowd_reports'
      and column_name = 'station_id'
  ) then
    alter table public.crowd_reports rename column station_id to stop_id;
  end if;
end $$;

create index if not exists idx_crowd_reports_stop_created_at
on public.crowd_reports (stop_id, created_at desc);

create index if not exists idx_crowd_reports_stop_source_created_at
on public.crowd_reports (stop_id, source_type, created_at desc);

do $$
begin
  alter table public.crowd_reports
    add constraint crowd_reports_stop_fk
    foreign key (stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

alter table public.crowd_reports enable row level security;

drop policy if exists "anon can read crowd reports" on public.crowd_reports;
create policy "anon can read crowd reports"
on public.crowd_reports
for select
to anon, authenticated
using (true);

drop policy if exists "anon can insert user crowd reports" on public.crowd_reports;
drop policy if exists "authenticated can insert user crowd reports" on public.crowd_reports;

create or replace function public.submit_crowd_report(
  p_stop_id text,
  p_source_type text default 'user',
  p_occupancy_level integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_stop_id text := public.normalize_stop_id(p_stop_id);
  v_source_type text := lower(trim(coalesce(p_source_type, 'user')));
  v_occupancy_level smallint;
  v_created_at timestamptz;
begin
  if v_stop_id = '' then
    raise exception 'stop_id is required';
  end if;

  if v_source_type not in ('user', 'delay') then
    raise exception 'Unsupported crowd report source type: %', v_source_type;
  end if;

  if not exists (
    select 1
    from public.transit_stops ts
    where ts.stop_id = v_stop_id
  ) then
    raise exception 'Unknown stop_id: %', v_stop_id;
  end if;

  if exists (
    select 1
    from public.crowd_reports cr
    where cr.stop_id = v_stop_id
      and cr.source_type = v_source_type
      and cr.created_at >= now() - interval '30 seconds'
  ) then
    raise exception 'Please wait before submitting another report for this stop.';
  end if;

  v_occupancy_level := case
    when v_source_type = 'delay' then 0
    else greatest(1, least(coalesce(p_occupancy_level, 3), 5))
  end;

  insert into public.crowd_reports (
    stop_id,
    occupancy_level,
    source_type
  )
  values (
    v_stop_id,
    v_occupancy_level,
    v_source_type
  )
  returning created_at into v_created_at;

  return jsonb_build_object(
    'stop_id', v_stop_id,
    'occupancy_level', v_occupancy_level,
    'source_type', v_source_type,
    'created_at', v_created_at
  );
end;
$$;

grant execute on function public.submit_crowd_report(text, text, integer)
to anon, authenticated;

-- 4) crowd_forecast_setup.sql
create table if not exists public.crowd_forecast_hourly (
  id bigint generated by default as identity primary key,
  stop_id text not null,
  forecast_hour smallint not null check (forecast_hour between 0 and 23),
  is_weekend boolean not null,
  occupancy_level smallint not null check (occupancy_level between 0 and 5),
  occupancy_percent numeric(5,2) not null check (occupancy_percent between 0 and 100),
  expected_wait_minutes smallint not null default 4 check (expected_wait_minutes between 0 and 60),
  eta_multiplier numeric(4,2) not null default 1.00 check (eta_multiplier between 1.00 and 3.00),
  source_type text not null default 'trend_model',
  updated_at timestamptz not null default now(),
  unique (stop_id, forecast_hour, is_weekend)
);

update public.crowd_forecast_hourly
set
  stop_id = public.normalize_stop_id(stop_id),
  source_type = lower(trim(source_type))
where true;

create index if not exists idx_crowd_forecast_stop_hour_weekend
on public.crowd_forecast_hourly (stop_id, forecast_hour, is_weekend);

do $$
begin
  alter table public.crowd_forecast_hourly
    add constraint crowd_forecast_hourly_stop_fk
    foreign key (stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

alter table public.crowd_forecast_hourly enable row level security;

drop policy if exists "anon can read hourly crowd forecasts" on public.crowd_forecast_hourly;
create policy "anon can read hourly crowd forecasts"
on public.crowd_forecast_hourly
for select
to anon, authenticated
using (true);

-- 5) randomized_crowd_predictions_seed.sql
insert into public.crowd_reports (
  stop_id,
  occupancy_level,
  source_type,
  created_at
)
select
  s.stop_id,
  case
    when rnd < 0.18 then 0
    when rnd < 0.52 then 1
    when rnd < 0.82 then 2
    else 3
  end as occupancy_level,
  case
    when random() < 0.30 then 'user'
    else 'predicted'
  end as source_type,
  now() - ((g.sample_no - 1) * interval '10 minutes')
from (
  select stop_id
  from public.transit_stops
) s
cross join lateral generate_series(1, 6) as g(sample_no)
cross join lateral (
  select random() as rnd
) r;

create or replace view public.station_crowd_trend as
select
  stop_id,
  count(*) as sample_count,
  count(*) filter (where source_type = 'user') as user_report_count,
  round(avg(occupancy_level)::numeric, 2) as avg_level_24h,
  max(created_at) as latest_report_at
from public.crowd_reports
where created_at >= now() - interval '24 hours'
group by stop_id;
