-- Run these blocks in order inside the Supabase SQL Editor.

-- 1) route_connections_setup.sql
create table if not exists public.route_connections (
  id bigint generated by default as identity primary key,
  from_stop_id text not null,
  to_stop_id text not null,
  route_id text not null,
  connection_type text not null default 'standard_stop',
  travel_time_minutes integer not null default 2,
  created_at timestamptz not null default now(),
  unique (from_stop_id, to_stop_id, route_id, connection_type)
);

alter table public.route_connections enable row level security;

drop policy if exists "route_connections_select_anon" on public.route_connections;
create policy "route_connections_select_anon"
  on public.route_connections
  for select
  to anon, authenticated
  using (true);

select count(*) as route_connections_count
from public.route_connections;

-- 2) find_route_rpc_setup.sql
create or replace function public.find_route(start_stop text, end_stop text)
returns table(path_array text[], total_time integer)
language sql
security definer
set search_path = public
as $$
  with recursive paths as (
    select
      array[upper(trim(rc.from_stop_id)), upper(trim(rc.to_stop_id))]::text[] as path_array,
      upper(trim(rc.to_stop_id)) as current_stop,
      rc.travel_time_minutes as total_time,
      1 as depth
    from public.route_connections rc
    where upper(trim(rc.from_stop_id)) = upper(trim(start_stop))

    union all

    select
      p.path_array || upper(trim(rc.to_stop_id)),
      upper(trim(rc.to_stop_id)) as current_stop,
      p.total_time + rc.travel_time_minutes as total_time,
      p.depth + 1 as depth
    from paths p
    join public.route_connections rc
      on upper(trim(rc.from_stop_id)) = p.current_stop
    where p.depth < 40
      and not (upper(trim(rc.to_stop_id)) = any (p.path_array))
  )
  select
    path_array,
    total_time
  from paths
  where current_stop = upper(trim(end_stop))
  order by total_time asc, cardinality(path_array) asc
  limit 1;
$$;

grant execute on function public.find_route(text, text) to anon, authenticated;

-- 3) crowd_reports_setup.sql
create table if not exists public.crowd_reports (
  id bigint generated by default as identity primary key,
  stop_id text not null,
  occupancy_level smallint not null check (occupancy_level between 0 and 3),
  source_type text not null default 'predicted',
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'crowd_reports'
      and column_name = 'source_type'
  ) then
    alter table public.crowd_reports
      drop constraint if exists crowd_reports_source_type_check;
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'crowd_reports'
      and column_name = 'station_id'
  ) then
    alter table public.crowd_reports rename column station_id to stop_id;
  end if;
end $$;

create index if not exists idx_crowd_reports_stop_created_at
on public.crowd_reports (stop_id, created_at desc);

alter table public.crowd_reports enable row level security;

drop policy if exists "anon can read crowd reports" on public.crowd_reports;
create policy "anon can read crowd reports"
on public.crowd_reports
for select
to anon
using (true);

drop policy if exists "anon can insert user crowd reports" on public.crowd_reports;
create policy "anon can insert user crowd reports"
on public.crowd_reports
for insert
to anon
with check (
  source_type in ('user', 'delay')
  and occupancy_level between 0 and 3
);

-- 4) randomized_crowd_predictions_seed.sql
insert into public.crowd_reports (
  stop_id,
  occupancy_level,
  source_type,
  created_at
)
select
  s.stop_id,
  case
    when rnd < 0.18 then 0
    when rnd < 0.52 then 1
    when rnd < 0.82 then 2
    else 3
  end as occupancy_level,
  case
    when random() < 0.30 then 'user'
    else 'predicted'
  end as source_type,
  now() - ((g.sample_no - 1) * interval '10 minutes')
from (
  select distinct upper(trim(stop_id)) as stop_id
  from public.train_stops_kl
  where stop_id is not null
    and trim(stop_id) <> ''
) s
cross join lateral generate_series(1, 6) as g(sample_no)
cross join lateral (
  select random() as rnd
) r;

create or replace view public.station_crowd_trend as
select
  stop_id,
  count(*) as sample_count,
  count(*) filter (where source_type = 'user') as user_report_count,
  round(avg(occupancy_level)::numeric, 2) as avg_level_24h,
  max(created_at) as latest_report_at
from public.crowd_reports
where created_at >= now() - interval '24 hours'
group by stop_id;
