-- 1) Create the route_connections table if it does not exist.
create table if not exists public.route_connections (
  id bigint generated by default as identity primary key,
  from_stop_id text not null,
  to_stop_id text not null,
  route_id text not null,
  connection_type text not null default 'standard_stop',
  travel_time_minutes integer not null default 2,
  created_at timestamptz not null default now(),
  unique (from_stop_id, to_stop_id, route_id, connection_type)
);

update public.route_connections
set
  from_stop_id = public.normalize_stop_id(from_stop_id),
  to_stop_id = public.normalize_stop_id(to_stop_id),
  route_id = upper(trim(route_id)),
  connection_type = lower(trim(connection_type))
where true;

create index if not exists idx_route_connections_from_stop
on public.route_connections (from_stop_id);

create index if not exists idx_route_connections_to_stop
on public.route_connections (to_stop_id);

do $$
begin
  alter table public.route_connections
    add constraint route_connections_from_stop_fk
    foreign key (from_stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.route_connections
    add constraint route_connections_to_stop_fk
    foreign key (to_stop_id) references public.transit_stops(stop_id) not valid;
exception
  when duplicate_object then null;
end $$;

-- 2) Enable RLS and allow app (anon/authenticated) read access.
alter table public.route_connections enable row level security;

drop policy if exists "route_connections_select_anon" on public.route_connections;
create policy "route_connections_select_anon"
  on public.route_connections
  for select
  to anon, authenticated
  using (true);

-- Optional: if you need to repopulate from scratch, uncomment next line.
-- truncate table public.route_connections;

-- 3) Verify the table exists (expect 0 before inserts).
select count(*) as route_connections_count
from public.route_connections;
